#!/usr/bin/env sh

echo "Running functions checks..."
npx tsc --noEmit || exit 1
npm run lint || exit 1
npx prettier --check functions lib || exit 1

echo "Running frontend checks..."
cd frontend || exit 1
npx tsc --noEmit || exit 1
npm run lint || exit 1
npx prettier --check src || exit 1
cd ..

echo "All checks passed."
